env:
  global:
    - LANG:tr_TR.UTF-8

language: php

php:
    - 5.6
    - 7.0

before_script:
    - phpenv rehash
    - composer install

script:
    - find ./src/ -name "*.php" -exec php -l {} \;
    - vendor/bin/phpcs --standard=PSR2 --report=full src
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text
